parameters:
  - name: serviceName
    type: string
  - name: buildConfiguration
    type: string
    default: 'Release'

steps:
  - task: UseDotNet@2
    displayName: '[${{ parameters.serviceName }}] Setup .NET'
    inputs:
      packageType: 'sdk'
      version: $(dotnetVersion)

  - task: DotNetCoreCLI@2
    displayName: '[${{ parameters.serviceName }}] Run Integration Tests'
    inputs:
      command: test
      projects: 'tests/Chatter.IntegrationTests.${{ parameters.serviceName }}/*.csproj'
      arguments: >
        --configuration ${{ parameters.buildConfiguration }}
        --collect:"XPlat Code Coverage"
        -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
      publishTestResults: true

  - task: PublishCodeCoverageResults@2
    displayName: '[${{ parameters.serviceName }}] Publish Coverage'
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - task: Docker@2
    condition: eq(variables.isPush, 'true')
    displayName: '[${{ parameters.serviceName }}] Build & Push Presentation Image'
    inputs:
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: '$(dockerHubNamespace)/chatter-${{ lower(parameters.serviceName) }}-presentation'
      command: buildAndPush
      Dockerfile: 'src/Chatter.${{ parameters.serviceName }}.Presentation/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        $(tag)
        latest

  - task: Docker@2
    condition: eq(variables.isPush, 'true')
    displayName: '[${{ parameters.serviceName }}] Build & Push Gateaway Image'
    inputs:
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: '$(dockerHubNamespace)/chatter-${{ lower(parameters.serviceName) }}-gateaway'
      command: buildAndPush
      Dockerfile: 'src/Chatter.${{ parameters.serviceName }}.Gateaway/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        $(tag)
        latest