parameters:
  - name: buildConfiguration
    type: string
    default: 'Release'

steps:
  - task: UseDotNet@2
    displayName: '[SyncKeycloakEventsJob] Setup .NET'
    inputs:
      packageType: 'sdk'
      version: $(dotnetVersion)

  - task: Docker@2
    condition: eq(variables.isPush, 'true')
    displayName: '[SyncKeycloakEventsJob] Build & Push Docker Image'
    inputs:
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: '$(dockerHubNamespace)/chatter-sync-keycloak-events-job'
      command: buildAndPush
      Dockerfile: 'src/Chatter.SyncKeycloakEventsJob/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        $(tag)
        latest